---
- hosts: all

  tasks:
  - name: Set authorized key from url
    authorized_key:
      user: vagrant 
      state: present
      #Replace this with a link to your own SSH pubkey
      key: https://gist.githubusercontent.com/casept/4704735c70870f26c942a08cdaedfbda/raw/37922cf65126bc0d38b52a818ce97617f7f4ad85/gistfile1.txt 

    
...
